### ISSUE TITLE
Set actual value format independently

### ISSUE THREAD

**Issue by ahkhanjani** [omeralpi/shadcn-phone-input#11]
Hi,

Is it possible to add the ability to set the field's value formatting (not display value) to something like E.164 etc.? Manually doing it throws and invalidated the country code for some reason. Probably skill issues on my side. But it would be nice to have that built in.

**Comment by omeralpi** [comment]
Hi, 

Is it like this?

```js
import { parsePhoneNumber } from "react-phone-number-input";

const parsedPhoneNumber: PhoneNumber | undefined = parsePhoneNumber("+905354511357");
```

```json
{
        "country": "TR",
        "countryCallingCode": "90",
        "nationalNumber": "5354511357",
        "number": "+905354511357",
        "__countryCallingCodeSource": "FROM_NUMBER_WITH_PLUS_SIGN"
}
```

```typescript
PhoneNumber {
  country?: CountryCode;
  countryCallingCode: CountryCallingCode;
  nationalNumber: NationalNumber;
  number: E164Number;
}
```

**Comment by ahkhanjani** [comment]
> Hi,
> 
> Is it like this?
> 
> ```js
> import { parsePhoneNumber } from "react-phone-number-input";
> 
> const parsedPhoneNumber: PhoneNumber | undefined = parsePhoneNumber("+905354511357");
> ```
> 
> ```json
> {
>         "country": "TR",
>         "countryCallingCode": "90",
>         "nationalNumber": "5354511357",
>         "number": "+905354511357",
>         "__countryCallingCodeSource": "FROM_NUMBER_WITH_PLUS_SIGN"
> }
> ```
> 
> ```ts
> PhoneNumber {
>   country?: CountryCode;
>   countryCallingCode: CountryCallingCode;
>   nationalNumber: NationalNumber;
>   number: E164Number;
> }
> ```

I don't quite understand what you mean by this. What I'm trying to say would be something like:

```tsx
<PhoneInput {...props} outputFormat="E.164" />
```

Is this what you're asking? Could you please elaborate?
