### ISSUE TITLE
For some reason the input appears as disabled

### ISSUE THREAD

**Issue by ZeldOcarina** [omeralpi/shadcn-phone-input#12]
Selecting a flag doesn't give any outcome. Do you have any idea?

![image](https://github.com/omeralpi/shadcn-phone-input/assets/42982095/0c58e146-1d60-481c-8c82-9b0f7e1c933a)

**Comment by omeralpi** [comment]
Hi.

1. Could you please provide details about the browser you are using?
2. Would you be able to record a screen video regarding the issue you are experiencing?

**Comment by ZeldOcarina** [comment]
Of course! I am using Chrome on latest version, here's a Loom:
https://www.loom.com/share/564ff3509a0648b18510e0aed2a5d4da?sid=27499613-6e64-4950-9833-75540200f501

Here's a snippet of the implementation:

```jsx
<FormField
          control={form.control}
          name="phoneNumber"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Phone Number</FormLabel>
              <FormControl>
                <PhoneInput
                  placeholder="Enter a phone number"
                  {...field}
                  className="w-full"
                  defaultCountry="US"
                  disabled={false}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
```

Except for a border radius change the `phone-input.tsx` is exactly what you gave in the repo! :)

Thanks for this project btw it's something I wanted to do but did not have time to!

**Comment by omeralpi** [comment]
The cause of your issue could be the Google extensions you're using. Have you tried opening it in an incognito tab? 🤔

> Of course! I am using Chrome on latest version, here's a Loom: https://www.loom.com/share/564ff3509a0648b18510e0aed2a5d4da?sid=27499613-6e64-4950-9833-75540200f501
> 
> Here's a snippet of the implementation:
> 
> ```js
> <FormField
>           control={form.control}
>           name="phoneNumber"
>           render={({ field }) => (
>             <FormItem>
>               <FormLabel>Phone Number</FormLabel>
>               <FormControl>
>                 <PhoneInput
>                   placeholder="Enter a phone number"
>                   {...field}
>                   className="w-full"
>                   defaultCountry="US"
>                   disabled={false}
>                 />
>               </FormControl>
>               <FormMessage />
>             </FormItem>
>           )}
>         />
> ```
> 
> Except for a border radius change the `phone-input.tsx` is exactly what you gave in the repo! :)
> 
> Thanks for this project btw it's something I wanted to do but did not have time to!


Have you tried opening it in an incognito tab with your Google extensions? 🤔

**Comment by omeralpi** [comment]
The cause of your issue could be the Google extensions you're using. Have you tried opening it in an incognito tab?

**Comment by ZeldOcarina** [comment]
I did not. I tried now but the outcome is the same..

**Comment by omeralpi** [comment]
Got it.

Make sure you have version "^0.2.1" of "cmdk" in your package.json file.

**Comment by Justbeingjustin** [comment]
I had the same problem and changing the version of cmdk  to "^0.2.1" did the trick.
