### ISSUE TITLE
Fix import InputProps

### ISSUE THREAD

**Issue by Reyes06** [omeralpi/shadcn-phone-input#14]
Hi friend, i had de next problem with the phone-input.tsx
![image](https://github.com/omeralpi/shadcn-phone-input/assets/34323946/4db6df86-e75c-4b84-97eb-23674859e3f4)
![image](https://github.com/omeralpi/shadcn-phone-input/assets/34323946/527031d0-ad28-4f43-b8db-35a3c69ee0fa)

And I just corrected it this way
![image](https://github.com/omeralpi/shadcn-phone-input/assets/34323946/5a9ffd03-630a-435c-b3be-99d154feaea3)

You are doing a good job, congratulations, keep it up

**Comment by omeralpi** [comment]
Hi.

See #12 

You're welcome.

**Comment by Reyes06** [comment]
I see that the problem described in that forum is different, the button showed them the popover but did not let them select something within it, in my case it did not show the popover when I clicked on the select button.

Dependencies installed:
![image](https://github.com/omeralpi/shadcn-phone-input/assets/34323946/64a243ef-9249-406a-82d1-d4df3b41d142)

**Comment by omeralpi** [comment]
If the version of the cmdk package is 1.0.0, please consider the descriptions in the README.md file.

> [!WARNING] 
> Before you dive in, just double-check that you're using version 0.2.1 of the cmdk package!

**Comment by omeralpi** [comment]
Thank you for your reminder about `import type` I've corrected it. 🎉
