### ISSUE TITLE
Popover scroll not working

### ISSUE THREAD

**Issue by lucas-nd** [omeralpi/shadcn-phone-input#16]
Popover scroll not working when using mouse. 

https://www.loom.com/share/abd87874b683454798636dafee7edbdb

"react-phone-number-input": "^3.3.9"
"@radix-ui/react-popover": "^1.0.7"
"cmdk": "^0.2.1"

I'm using Google Chrome, but I also tested it on Edge

**Comment by omeralpi** [comment]
Hi, 

You can follow the issue below; 💪
https://github.com/shadcn-ui/ui/issues/542

I'm also looking into it. 🧐
