### ISSUE TITLE
Do we have react native equivalent for this library?

### ISSUE THREAD

**Issue by kuldip-simform** [omeralpi/shadcn-phone-input#18]
I am developing an app in React Native, and I have checked out so many phone-inputs but nothing seems to work perfectly or in real-time. Some of them are actually pretty slow at formatting numbers while typing so if you have any idea how I can use this package in React Native, that would be helpful.
Thank you.

**Comment by kuldip-simform** [comment]
HI @omeralpi Can you please reply to my question if I can use this tool in react native or do you have plan to add support for react-native?

**Comment by omeralpi** [comment]
> HI @omeralpi Can you please reply to my question if I can use this tool in react native or do you have plan to add support for react-native?

Hi, 

React Native does not support it and it does not seem possible in the future either. 

You can look into alternative packages. https://www.npmjs.com/package/react-native-phone-number-input

**Comment by kuldip-simform** [comment]
@omeralpi  I am using that package in my project. Thank you for your response.
