### ISSUE TITLE
any param to make countries select to be active ? 

### ISSUE THREAD

**Issue by antsav** [omeralpi/shadcn-phone-input#20]
latest installation

![Screenshot 2024-04-03 at 9 07 20 PM](https://github.com/omeralpi/shadcn-phone-input/assets/1043531/b1382a2e-8d02-43e5-920d-4816d2fa75cc)

**Comment by omeralpi** [comment]
Hi.

See #12 

If the version of the cmdk package is 1.0.0, please consider the descriptions in the README.md file.

> [!WARNING] 
> Before you dive in, just double-check that you're using version 0.2.1 of the cmdk package!
