### ISSUE TITLE
Command bar for selecting country is disabled when trying to select country

### ISSUE THREAD

**Issue by Paul-Okello** [omeralpi/shadcn-phone-input#26]
![issue](https://github.com/omeralpi/shadcn-phone-input/assets/42891966/a45cc28d-cc46-4ff6-84f4-0f5ee4205fdf)

**Comment by edbella** [comment]
Hi @Paul-Okello 

This is not an issue with this package but an issue with the `CommandItem` component. An incorrect tailwind state of `data-[disabled]` was defined which activates on default. You need to change it to `data-[disabled=true]` to fix this issue

**Comment by omeralpi** [comment]
fixes #30
