### ISSUE TITLE
Country Select Popover options are disabled

### ISSUE THREAD

**Issue by hameeedurrehman** [omeralpi/shadcn-phone-input#39]
I implemented this shadcn-phone-input in my project using the code snippet provided here: 
https://shadcn-phone-input.vercel.app/#try
converted tsx file to jsx, every thing is fine just except the country code options are disabled, I can't select any option.

**Comment by WilliamBlais** [comment]
This is unrelated to shadcn-phone-input, please see https://github.com/shadcn-ui/ui/issues/2944#issuecomment-2226357010

**Comment by pankajyadav05** [comment]
@WilliamBlais Worked for me, Thank

**Comment by hameeedurrehman** [comment]
@WilliamBlais Thanks. Got it!
