### ISSUE TITLE
Can not use mouse to select country

### ISSUE THREAD

**Issue by ngogiahuandev** [omeralpi/shadcn-phone-input#41]
Hi, I just create project with shadcn, nextjs then i do the tutorial on the document but i cannot select the country by mouse, i had to use keyboard to select, it look like the select is disabled, anyone have this issue, please help

this is the capture
![image](https://github.com/user-attachments/assets/6f1ff8c5-8698-411d-b7f7-86cb00508ea8)

**Comment by ukeskin** [comment]
I have the same problem
