### ISSUE TITLE
Cannot select countries from the Popup (Looks like they are disabled)

### ISSUE THREAD

**Issue by NirbhaySirsikar** [omeralpi/shadcn-phone-input#42]
## This is how it looks:

![image](https://github.com/user-attachments/assets/4f10eff5-9a81-47c0-9ab5-677dcd62865b)

## And I am using it like this:

```
            <FormField
              control={form.control}
              name="phone"
              render={({ field }) => (
                <FormItem >
                  <FormLabel >Phone Number</FormLabel>
                  <FormControl>
                    <PhoneInput
                      defaultCountry="IN"
                      placeholder="Enter a phone number"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
```

## Issue:

I can't click on them, can't select, they look disabled, tried passing parameter disabled={false} but didn't work

**Comment by NirbhaySirsikar** [comment]
I found the solution, but this might happen to other new users too.
this package only works with ``` "cmdk": "^0.2.1" ``` 
I installed the latest version 1.0.0 and it didn't work

**Comment by llPekoll** [comment]
> I found the solution, but this might happen to other new users too. this package only works with `"cmdk": "^0.2.1"` I installed the latest version 1.0.0 and it didn't work

Thanks @NirbhaySirsikar Worked for me ;)
