### ISSUE TITLE
Server side zod schema

### ISSUE THREAD

**Issue by fsiatama** [omeralpi/shadcn-phone-input#5]
Hello,

I've encountered an issue when using server actions with Next.js and attempting to validate phone numbers on the server side.

Currently, the documentation/code suggests using:

`
import { isValidPhoneNumber } from "react-phone-number-input";
`

However, this import is client-side oriented and might not be suitable for server-side validations due to its dependency on the react-phone-number-input package, which is primarily designed for client-side React applications.

For server-side validations within Next.js server actions, it's more appropriate to use:

`
import { isValidPhoneNumber } from 'libphonenumber-js';
`

**Comment by ahkhanjani** [comment]
Hi,

I think this could be mentioned in the readme for the time being.
